### ISSUE TITLE
Delay when opening backstage when launching application if backstage is open by default.

### ISSUE THREAD

**Issue by TylerKalosza** [fluentribbon/Fluent.Ribbon#105]
We just upgraded a project from Fluent Ribbon 2.0.2 to 3.4.0.  In the program we code it so the backstage is open by default.  In version 2.0.2 the backstage was immediately presented on launch.  In version 3.4.0 there is a slight delay to showing the backstage, the program launches with the backstage closed and the user sees the workspace with the first ribbon tab displayed, then the backstage appears after a short time, the time varies between a quarter of a second and maybe a second (estimated times).

I'm not sure if this is a bug or something that I'm doing incorrectly.

I have tried 2 approaches, since I am using the MVVM design pattern in my application I have a view model with an IsBackstageOpen property that is set to true by default and bound to the backstage's IsOpen property:
```XAML
<fluent:Backstage Header="File" IsOpen="{Binding IsBackstageOpen, Mode=TwoWay}" Background="{Binding BackstageTabBackgroundColor, Mode=OneWay}">
```

I have also tried this but got the same result:
```XAML
<fluent:Backstage Header="File" IsOpen="True" Background="{Binding BackstageTabBackgroundColor, Mode=OneWay}">
```

Any suggestions or information on this would be greatly appreciated!  Thanks in advance!

**Comment by batzen** [comment]
It's this code that causes your problem:
```
private void OnDelayedShow(object sender, EventArgs args) 
{ 
	this.Loaded -= this.OnDelayedShow; 

	// Delaying show so everthing can load properly. 
	// If we don't run this in the background setting IsOpen=true on application start we don't have access to the Bastage from the BackstageTabControl. 
	this.RunInDispatcherAsync(this.Show, DispatcherPriority.Background); 
}
```

Which get's called when "Show" is called and the backstage is not currently loaded.

**Comment by TylerKalosza** [comment]
Thanks for the info.  Is there anything I can do to prevent this from happening?  Or am I out of luck in getting it to show instantly?

**Comment by batzen** [comment]
You could try to delay the dispatcher pressure caused by your main screen load by loading it with Application.Current.Dispatcher.BeginInvoke or something like that to cause the backstage to load faster. 

In fact i am doing so to increase the perceived application load time performance. That is, i am able to show the main window (including the ribbon) and loading it's content async in dispatcher. But i am not showing the backstage on startup so this might or might not work for you.

It might also depend on what you are showing in your backstage.
As of now the delay you are seeing is totally dependant on WPF to raise the loaded event for the backstage.

If you feel this should be investigated further on the ribbon side you could try to change the code to not wait for the loaded event and try to avoid the issue stated in the comment above the async invocation.

**Comment by batzen** [comment]
Any news on this one?

**Comment by TylerKalosza** [comment]
Sorry I haven't responded, I haven't really had time to investigate this.  I will try to go into work early on Monday and try a couple of things that you suggested.  I suspect this will not solve my issue, but it's worth a try.  Then I will close the issue once I'm either successful or unsuccessful.

**Comment by batzen** [comment]
Any news on this one?

**Comment by TylerKalosza** [comment]
Yes, I managed to thread my startup code so the backstage appears almost instantly, it seems to no longer be an issue for me.  Thanks!

**Comment by batzen** [comment]
Nice you figured it out!

**Comment by TylerKalosza** [comment]
Yea, I mean it's still not 100% instantaneous, but it definitely works for my needs.

**Comment by batzen** [comment]
Should be a bit faster after my last commit. At least it felt a little faster.

**Comment by TylerKalosza** [comment]
I saw that you released 3.4.1.  I'm excited to upgrade to it once I'm done the new feature I'm working on!

**Comment by batzen** [comment]
The commit I was talking about is for 3.4.2. Will release that version today.

**Comment by TylerKalosza** [comment]
Ooooooooo!  :grinning:

**Comment by batzen** [comment]
Released.
