### ISSUE TITLE
Unable to change foreground of the RibbonWindow

### ISSUE THREAD

**Issue by MrNorth35** [fluentribbon/Fluent.Ribbon#107]
Hi!

First of all, thanks for the awesome ribbon control. I am using it at a customer who wants a dark theme, hence we need to set the title text, and minimize/maximize/close buttons to a whitish color. I thought it was as simple as setting the Foreground property to White on the Fluent:RibbonWIndow tag, but that changed nothing.

We also had a similar issue when trying to change the background color of the Fluent:Statusbar. It just wouldn't take the Background property, which is kind of strange.

Would really appreciate some support on this, since we are almost finished with the application, and are in the styling phase and need to sort out these things.

We use the Office2013/Generic.xaml theme and everything is latest version from nuget.

regards
Henrik

**Comment by MrNorth35** [comment]
Hi!

I managed to workaround this by overriding the ControlTemplate for the RibbonTabItem, do please confirm that this the way to do it, because it would be much easier to just change "Background".

I guess I have to do the same for the StatusBar, which also doesn't react to a change in the "Background" property. 
Note that the fluent ribbon works perfect if you want a 100% Office2013 style, but sadly our customer has special needs...
/Cheers

**Comment by chdft** [comment]
You can change the global theme color using the code snippet below (replace #000000 with your theme color). That changes the color of status bars, backstages, etc.
```xaml
<Color x:Key="{x:Static Fluent:MetroColors.ThemeColorKey}">#000000</Color>
```
To make it apply globally, you have to merge it with the theme you use (Office2013/Generic.xaml in your case). That will look like this (in App.xaml):
```xaml
<ResourceDictionary.MergedDictionaries>
	<!--Attach Default Fluent Control's Theme-->
	<ResourceDictionary Source="pack://application:,,,/Fluent;Component/Themes/Generic.xaml" />
	<ResourceDictionary Source="pack://application:,,,/Fluent;Component/Themes/Office2013/Generic.xaml" />
	<ResourceDictionary Source="Design.xaml" /> <!-- this contains your changes to the Fluent theme -->
</ResourceDictionary.MergedDictionaries>
```
I don't know if this is the intended way, but it works and I've not seen any side effects.

**Comment by batzen** [comment]
To sum this up:
- To change the background of the StatusBar you currently have to modify the RibbonThemeColorBrush. This could be made easier on our side by setting this background on the Style level rather than the inner border or the control.
- Just changing the Background property on the RibbonTabItem wouldn't help much as you got many colors which are used there. Think of states like "Selected", "Hover" etc. those could, of course, all be exposed but there is nothing planned to implement it in that way. If you want to, feel free to open a new issue and discuss the details of such a change.
- To change the foreground: there is a "DefaultFontBrush" which you could change and see how far you can go with that. Duo to the history of this library, on one side, this was needed in the past. I can image that we could eliminate that one mostly. But we have to set some foreground color somewhere (maybe at the ribbon level) and as I don't need it that way (I can live with the current implementation) I won't change it. On the other side we got many different background colors and so we need different foreground colors. An easy way to be able to find foreground colors is to search for "FontBrush" and see which ones you need to change according to your requirements.

**Comment by MrNorth35** [comment]
Thanks for the information, we have solved it now and can proceed. Excellent support, thumbs up!
