### ISSUE TITLE
Is it possible to add and remove ribbon tabs in a MVVM architecture?

### ISSUE THREAD

**Issue by MrNorth35** [fluentribbon/Fluent.Ribbon#109]
Hello!

I haven't found an answer for this, so maybe it is not possible. We are using FLuent Ribbon in an MVVM architecture with PRISM 5.0. The ribbon is in a standard region with no special adapters or anything.

I noticed in your showcase demo that you add tabs programmatically in the code behind. We would like to handle this some other way, preferrably by describing each tab in xaml and then somehow add it from the ribbonviewmodel. My idea is that each view that has tabs implement some interface like IRibbonTabAware and when the PRISM Regionmanager navigates to a view with this interface, it checks if it implementsments this interface, and if it does either add or remove the view's ribbon tab. Most likely only the xaml, and the commands for any buttons on the tab have to be global in the ribbonviewmodel. 

Maybe I should add ALL tabs from the start and just show/hide them with a simple bool flag? Not pretty but might do the trick?

your ideas?

/Henrik

**Comment by chdft** [comment]
If you know all tabs at compile-time, it is probably the best idea to add them in xaml, because the gain by having a smaller visual tree is probably not worth the additional work. 
It also sounds like you might want to use contextual groups, which allow you to group tabs that are only useful/available in a certain context. That way the user gets a visual clue, that there are additional commands available based on the context. You can also easily hide entire `RibbonContextualTabGroup`s by setting their visibility property.
If you want to handle the `RibbonTabItem`s in the views, you can bind the `Tabs` property of the ribbon to a `ObservableCollection<RibbonTabItem>` which is composed and changed based on the current view in the code behind. You can access wpf resources with `this.Resources["yourKey"]` from the code behind, but if you define the tabs in a central xaml file anyway, you might as well just define them inside the ribbon of the target window (unless of course you will use the tabs in more than one window).

**Comment by batzen** [comment]
MVVM is not fully supported.
Have a look at https://github.com/fluentribbon/Fluent.Ribbon/issues/1
