### ISSUE TITLE
Read Only state for Ribbon Controls

### ISSUE THREAD

**Issue by cbra-caa** [fluentribbon/Fluent.Ribbon#1121]
In Office 2021 the ribbon controls have been made accessible to keyboard users, even when they are in a disabled state, IsReadOnly as opposed to IsEnabled.

![image](https://user-images.githubusercontent.com/47817657/230076278-4a1567ac-cf5b-46d1-a2ea-fe7e572b9cb6.png)

I would like to introduce this functionality into Fluent and have made a Proof of Concept for how it could be done, with a working example for the 'Button' control.

I am not very fluent (😅) in Git so currently I have just attached it as a Pull Request, if there is a better way, I'll be very interested. But for now I hope you can use it to see my idea and then just block it from being merged. 
I hope you think that this is worth continuing with, and if so, you can assign me the issue and I'll take the concept and apply it to the other Ribbon controls.

**Comment by batzen** [comment]
I think we shouldn't try to solve that feature/issue her, but in WPF itself instead.
The real problem is that WPF prevents focus on disabled controls.
Do you want to propose it there or should I try my luck?
I would argue with accessibility and the solution i have in mind would only require one new attached property and a few changed conditions.
That way it wouldn't even be a breaking change.

**Comment by cbra-caa** [comment]
If you can try your luck, I would appreciate that - your solutions sounds better too, the current one requires boilerplating the IsEnabled, Command property and OnClick for every control you want to implement the IsReadOnly state.

I can add some accessibility context to the issue, regarding both sight and motor-skills.
