### ISSUE TITLE
Fluent:Button Size Middle not working anymore

### ISSUE THREAD

**Issue by GinoDerycke** [fluentribbon/Fluent.Ribbon#1201]
Since update to 10.1.0, the Fluent:Button property Size="Middle" is not working anymore. It shows always as large. If I change by code the size to "Large" and then back to "Middle", it works.

### Environment

- Fluent.Ribbon __v10.1.0
- Windows 11
- .NET Framework 4.8

**Comment by batzen** [comment]
Setting `Size` will only work temporarily if the control is placed in a `RibbonGroupBox` as it interferes with automatic sizing.

If you want to force a certain size you have to set `SizeDefinition="Middle"` (for example) or `SizeDefinition="Middle,Small"` if you only want to prevent your control from being large.

The reason for this is that during measures of `RibbonGroupBox` sizes of controls have to be adjusted and as there is no way to know for sure if `Size` was set because of automatic sizing or was set manually the size is simply overwritten.

It worked more often in versions prior to 10.1, but essentially it was a bug that got fixed in 10.1 by being more consistent when measuring/sizing.

**Comment by GinoDerycke** [comment]
Ok, thank you. This works!

Greetings,

Gino

Op wo 1 mei 2024 07:22 schreef Bastian Schmidt ***@***.***>:
