### ISSUE TITLE
Reusing RibbonWindow 

### ISSUE THREAD

**Issue by bjvanhaaff** [fluentribbon/Fluent.Ribbon#127]
Hi

I'm trying to reuse the RibbonWindow trough out my application to have a consistent look with the ribbon style (for example for modal dialogs etc). However if I do not define a Ribbon element on the RibbonWindow, there is no window title and the content is overlapping with the window chrome. In the VS designer all looks fine.

Is there a workaround for this?

Thanks!
Bart

__Example:__

XAML:
````
<Fluent:RibbonWindow x:Class="TC.Client.Dialogs.Test"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:Fluent="clr-namespace:Fluent;assembly=Fluent"
        Title="This is the window title" Height="200" Width="300">
    <StackPanel>
        <GroupBox Header="Groupbox">
            <StackPanel>
            <RadioButton Margin="4">Radio 1</RadioButton>
                <RadioButton Margin="4">Radio 2</RadioButton>
                <RadioButton Margin="4">Radio 3</RadioButton>
                <RadioButton Margin="4">Radio 4</RadioButton>
            </StackPanel>
        </GroupBox>
        <StackPanel Orientation="Horizontal">
            <Button Width="100" Margin="5">OK</Button>
            <Button Width="100" Margin="5">Cancel</Button>
        </StackPanel>
    </StackPanel>
</Fluent:RibbonWindow>
````

Visual Studio:

![image](https://cloud.githubusercontent.com/assets/12606267/8160014/5f6bb226-136c-11e5-8819-337368a3d2a8.png)

Runtime:

![image](https://cloud.githubusercontent.com/assets/12606267/8160057/c10ec6ee-136c-11e5-9b9b-0fbe011bcfd9.png)

**Comment by batzen** [comment]
It looks different because we can't really overwrite the way the designer renders the window. As you can see in your screenshots the buttons for minimizing, maximizing and closing the window are missing in the designer.
To really use the RibbonWindow you have to add a Ribbon to the Window.
There are ways to, kind of, hide the ribbon from the window then and that's the way I use it at work.
The RibbonWindow has a property called IsCollapsed which you should set to "true" and IsAutomaticCollapseEnabled should be set to "false" for a starting point.

**Comment by batzen** [comment]
Can we close this or do you have further questions?
