### ISSUE TITLE
How to change main content when ribbontab is selected 

### ISSUE THREAD

**Issue by adharstellosys** [fluentribbon/Fluent.Ribbon#149]
How to change main content when ribbontab is selected 

Show different grid for different tab (Ribbon Tab) 
It works fine when i used normal tab control

**Comment by batzen** [comment]
That's because the RibbonTabControl is no double TabControl and already has a selected content. The selected content is the RibbonTabItem itself.

So to answer your question on how to change the main content when ribbontab is selected: 
You will have to do that by yourself.

In every app, I found so far, using a Ribbon works the other way around. There you got content and as the content changes the Ribbon changes things like Contextual groups etc..

Does that answer your question?

**Comment by adharstellosys** [comment]
Thanks for your reply. that was exactly i want to know
