### ISSUE TITLE
When item from Toolbar Dropdown is added with has click event the Click Event is not trigered (do not work).

### ISSUE THREAD

**Issue by Drasius2** [fluentribbon/Fluent.Ribbon#155]
When item from Toolbar Dropdown is added with has click event the Click Event is not trigered (do not work).

How to repeat:
Modify Fluent Ribbon source file (TestContent.xaml):
>
 \<Fluent:RibbonGroupBox Fluent:KeyTip.Keys="ZC"
                                       Header="Normal KeyTips"
                                       Name="ZC">
 ....
<Fluent:MenuItem Fluent:KeyTip.Keys="O"
Header="Orange"
Icon="pack://application:,,,/FluentTest;component/Images/Orange.png"
     
>**Click = MenuItem_OnClick** />   //Added click event to Orande menu item

And in cs code add method it self:
>private void MenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            MessageBox.Show("Menu 1 is Clicked");
        }

 Then if you add Parent levels Menu items with the Orange Menu as a child - the Click event will work. But if you Right Click on "Orange" menu item and add it to QAT - after this try to click QAT "Orange" icon, then the Orange menu Click Event is not fired.

**Comment by batzen** [comment]
If I get you correctly this does not work because we don't (or can't I don't know) copy the registered events to the new control.
To eliminate "If I get you correctly" it would be nice if you could provide a fully working repro. Feel free to combine this repro with repros from other issues you reported.

**Comment by Drasius2** [comment]
Hi, I changed code: you can take the repo: https://github.com/Drasius2/Fluent.Ribbon/tree/Branch_%23155.

To repeat:
1. Louch .net 4.5 version app.
2. Go to "KeyTips" tab menu
3. See image:
![image](https://cloud.githubusercontent.com/assets/3475668/9430025/d7116188-49ed-11e5-9a30-8f235c3b4cc4.png)

**Comment by batzen** [comment]
That's because click events are not always forwarded to their original control.

I would suggest you use Commands instead of Click events. Commands are always forwarded/copied.
The problem with copying event registrations or forwarding them is that those cause memory leaks because the original control, which creates the quick access item and has to forward the events, is currently not notified when that item is destroyed/remove from the QAT.

Does that make sense for you? English is not my native language...

**Comment by Drasius2** [comment]
Yes, thanks. So I am closing this.
