### ISSUE TITLE
SaveWindowPosition doesn't do anything.

### ISSUE THREAD

**Issue by Carlluna2001** [fluentribbon/Fluent.Ribbon#195]
I need to know if this function works. It seems to have no effect when I set its value to TRUE.

Please help

Carlos

**Comment by batzen** [comment]
Will have a look at this.

**Comment by batzen** [comment]
It's currently broken.
I guess I will just remove that whole functionality as no one ever seems to have used it.

**Comment by Carlluna2001** [comment]
It's weird that no one uses it. It is a very important feature since it is a must to save window size and position.

**Comment by batzen** [comment]
Maybe it's because it did not work or because it only is capable of saving one window position per application.
I never implemented it, just inherited it from someone else...
Ah, someone took the code from http://jake.ginnivan.net/remembering-wpf-window-positions/

Don't get me wrong when I say that I will remove that feature. It's just because I think this library should focus on the ribbon itself and not general purpose classes/features for saving window positions.

**Comment by Carlluna2001** [comment]
I see what you mean... Thanks for posting the link. I need to implement this feature in my application.

**Comment by batzen** [comment]
You could have a look at #196, maybe this feature will be available through a different OSS project.
