### ISSUE TITLE
Backstage disappears when changing DontUseDwm

### ISSUE THREAD

**Issue by huoyaoyuan** [fluentribbon/Fluent.Ribbon#228]
Office2010 theme only.
Restores when changing theme.
Can be reproduced by FluentTest.

**Comment by batzen** [comment]
Can't reproduce this in the develop branch which represents version 4.0 of this library.
Will release a pre-release nuget package this week so you can try it yourself.
Or, if you want to try it now, just clone the develop branch.
If you decide to clone the develop branch and try it, please tell me if your issue is still present there.
If it is still present there I need more information on how to reproduce your issue.

**Comment by huoyaoyuan** [comment]
I've cloned from the develop branch, but can still find this issue.
Steps to reproduce:
1. Run the showcase;
2. Change to a theme different with Office2013;
3. Now the Backstage works well; (__this issue will happen only when you check in this step__)
4. Change the RibbonWindow's DontUseDwm property using the checkbox;
5. Now the Backstage can't be shown(seems to behavior as Transparent);
6. Change to another theme, then everything goes correct; but if DontUseDwm changed __and you've opend BackStage before the change__, the BackStage will disappear again.
This doesn't happen only when using Office2013 theme, because DontUseDwm is currently seems no effect with it (v3.6.0 - develop). I remember that it takes effect in a previous version, maybe 3.4.2?
