### ISSUE TITLE
Add start screen like in office 2013 and upwards

### ISSUE THREAD

**Issue by batzen** [fluentribbon/Fluent.Ribbon#242]
As suggested in PR (#227) from @maurosampietro a start screen like in office 2013 and upwards should be implemented.

**Comment by batzen** [comment]
@maurosampietro could you have a look and see if I didn't miss something?

**Comment by maurosampietro** [comment]
Hi, i had a quick look this morning.
Everything is ok, works with and without dwm and WindowSteeringHelpeControl
solves titlebar issues in the left panel.

Although Office 2013 theme is perfect with and without dwm, it looks pretty
bad when using other themes.

I dont know how the StartScreen should look like with themes different than
Office 2013 since it did not exist before that version, but when switching
to Office 2010 or Windows 8 themes immediately note the following:

If "don't use dwm" is unchecked:
- Left panel's top border touches the main window border. This happen
with Silver, Blue and Black themes. (Applies to all themes different from
Office 2013)

- The startpage looks particularly bad when using BlackTheme:
[image: Immagine incorporata 1]

If "don't use dwm" is checked:
- Left panel's top border is ok.
- Left panel should have the same color/brush as the titlebar and window
borders; this is particularly noticeable with Blue and Silver themes. You
can have a look to black theme to have an idea of how it should look, even
though Black theme is not using the exactly same color/brush either.


I noticed you preferred to deal with a single generic style.
Maybe I should have pointed out i chose to make different styles per
theme instead of a generic one exactly to solve this issues separately in a
later moment.

Mauro Sampietro

Il giorno 10 gen 2016, alle ore 12:25, Bastian Schmidt <
notifications@github.com> ha scritto:

@maurosampietro <https://github.com/maurosampietro> could you have a look
and see if I didn't miss something?

—
Reply to this email directly or view it on GitHub
<https://github.com/fluentribbon/Fluent.Ribbon/issues/242#issuecomment-170336640>
.

**Comment by batzen** [comment]
The image is missing in your response.

As for the generic style: 
I just hate it to have to duplicate the whole template, and maintain all of them, just because there has to be one line with different values.

I will try to avoid duplicated templates from now on for everything and instead introduce new properties to the control where needed and differentiate by style settings.

As a side note, the generic solution has exactly the same color you chose.

The borders behave the same as the backstage in those themes, regarding the left border. It true that it stretches to the top border of the window, but that's how the start screen behaves in Office 2013 and upwards.

If anyone really uses the start screen with the office 2010 or windows 8 theme and complains about the border behavior/look I might think about a change, but not yet. ;-)

**Comment by maurosampietro** [comment]
I will try to fix those minor styling issues without template duplicates even though having different templates seemed the way to go in this particular case.

Can you please provide a name  of a control that already deals with style with properties as you described, just so i can use it as example?

Thank you!


Mauro Sampietro
Inviato da iPhone

**Comment by batzen** [comment]
Even though the BackstageTabControl uses different templates it also has properties dedicated for styling. For example ItemsPanelBackground.

Which styling issues are you planning to fix?

**Comment by maurosampietro** [comment]
Dwm disabled in Office 2010 theme issues i described previously

Mauro Sampietro
Inviato da iPhone

**Comment by batzen** [comment]
Ah, now I got it.
If you haven't already started i could give it a try.

**Comment by batzen** [comment]
Just had a look. Fixing that one will be a bit more difficult as it depends on properties only available on the window itself...

**Comment by batzen** [comment]
So from my point of view this looks kinda finished.
Anything you think that still has to be done?

**Comment by maurosampietro** [comment]
We can close. Good job!

Mauro Sampietro
Inviato da iPhone
