### ISSUE TITLE
How to change the font color of Contextual tabs?

### ISSUE THREAD

**Issue by Rizelle** [fluentribbon/Fluent.Ribbon#308]
I tried setting other colors than Black in Foreground property but nothing happens.
Am I missing something?

**Comment by batzen** [comment]
The sample application has contextual tabs with different foreground color.

```
<Fluent:RibbonContextualTabGroup x:Name="tabGroup1"
                                    BorderBrush="Magenta"
                                    Background="Magenta"
                                    Foreground="Purple"
                                    Header="FIRST"
                                    Visibility="Visible" />
```

**Comment by Rizelle** [comment]
Just realized I'm still using an older version.
Will try to get the latest version and check this again.

Thanks.

**Comment by Rizelle** [comment]
I'm sorry. Still doesn't work.

**Comment by batzen** [comment]
Then i will need a repro from you.

**Comment by batzen** [comment]
@Rizelle any chance to get a repro from you?

**Comment by batzen** [comment]
Any news?

**Comment by batzen** [comment]
Any news?

**Comment by Dany-R** [comment]
Hi, 
because there has been no answer from Rizelle yet, I can confirm, that the `Foreground` property of the `RibbonContextualTabGroup` sets the text color of the group header as well as the header text color of the **selected** contextual tab. The **unselected** contextual tab header gets its text color from the `Foreground` property of the `RibbonTabItem`.
Cheers, Dany _(Fluent.Ribbon rookie)_
