### ISSUE TITLE
Office2013 blue theme?

### ISSUE THREAD

**Issue by esmonica** [fluentribbon/Fluent.Ribbon#367]
--
### Environment

- Fluent.Ribbon __v 5.0.0.0
- Theme __?__ (not needed in version 5.0 and upwards)
- Windows 10
- .NET Framework 4.0

Hello,

I used to use the  office 2010 blue theme,
`<ResourceDictionary Source="pack://application:,,,/Fluent;Component/Themes/Office2010/Blue.xaml" />`

but I believe that this has been removed altogether, and that now it will be Office2013. So I tried:

`<ResourceDictionary Source="pack://application:,,,/Fluent;Component/Themes/Office2013/Blue.xaml" />`

but the resource dictionary is not found in the fluent ribbon 5.0.0.0. So at the moment I have:

`<ResourceDictionary Source="pack://application:,,,/Fluent;Component/Themes/Generic.xaml" />
`

I would really like to use a blue theme. Has this just been removed altogether or how can I have the ribbon tab items as blue? Many thanks

**Comment by batzen** [comment]
There is currently no blue theme for office 2013.

My plan was to introduce new color schemes in a version after 5.0, but i got no schedule for the color schemes.

You could also try to create your own color scheme.
Basically you would only need to overwrite the colors which are present in `Colors.xaml`.
Some colors currently can't be overwritten because they are hard coded in some styles/templates.
I will improve that situation over time, but as i am fine with the current color scheme it's not on top of my todo list.

**Comment by esmonica** [comment]
Many thanks batzen for your quick reply and direction
