### ISSUE TITLE
How can i set Properties of the Back-Button of the Backstage?

### ISSUE THREAD

**Issue by juergschweigi** [fluentribbon/Fluent.Ribbon#374]
Hallo,
i want to set the Back-Button of the Backstage to disabled or Visibility.Hidden. 
How can I do this programatically?

**Comment by batzen** [comment]
The button is inside the `BackstageTabControl` and it's name is `backbutton`.
The is no implemented way to hide it.

But depending on what you are trying to achieve it might be better to use the `StartScreen` instead of `Backstage`.
`StartScreen` and `StartScreenTabControl` have no back-button by default.
