### ISSUE TITLE
Assign a StringFormat binding to a Button Header

### ISSUE THREAD

**Issue by LaborJos** [fluentribbon/Fluent.Ribbon#375]
Button Header Binding StringFormat does not apply.

### Environment

- Fluent.Ribbon __4.0.3.394__
- Theme __Office2013/Generic__ (not needed in version 5.0 and upwards)
- Windows __8.1__
- .NET Framework __4.5__

**Comment by batzen** [comment]
That's true and won't be possible.
The reason is that `Header` is of type object, so you can place whatever you want in it.
The binding engine in WPF is responsible for applying `StringFormat` on bindings. To be able to do this there is a type check for the corresponding `DependencyProperty`. If the `DependencyProperty` is of type `string` the `StringFormat` is used. If it's not of type `string` the `StringFormat` is ignored completely.
See https://referencesource.microsoft.com/#PresentationFramework/src/Framework/System/Windows/Data/BindingExpressionBase.cs,7447fc99cc85c66b,references
