### ISSUE TITLE
ContextualGroups and RibbonTabItem's Visibility and IsSelected controlled by code.

### ISSUE THREAD

**Issue by Yumeryu** [fluentribbon/Fluent.Ribbon#420]
Goal:
When selected item changed by combo box or by code (ie from other button actions.), make RibbonTabItem "show and selected" or "disappear and select home tab".

Issues: 
When selected item changes, ContextualGroups appears but RibbonTabItem is not selected, even the ContextualGroups' Visibility binding is based on the boolean value which RibbonTabItem's IsSelected bind to.

Sample project included, by clicking the 3 buttons on screen, you can see the ContextualGroups reacting different.

Thanks in advance.

[WpfApplication1.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/890026/WpfApplication1.zip)

---
### Environment

- Fluent.Ribbon __latest code
- Theme __?__ (not needed in version 5.0 and upwards)
- Windows __10__
- .NET Framework __4.5__

**Comment by Yumeryu** [comment]
Any chance this can be looked at please? Thanks.

**Comment by batzen** [comment]
I am always trying to look at issues as fast as I can.
Please do not try to pressure me. My regular reaction to pressure here is to ignore the people causing it.

**Comment by batzen** [comment]
This issue is two sided. I can lessen the negative effects a bit, but it's mainly caused by your code.

Problem:
You set the bindings for your `IsSelected...Tab` to `OneWay` which will never completely work out using the ribbon because your code is not the only party having to change `IsSelected` on `RibbonTabItem`. You have to use `TwoWay` to allow the `Ribbon` to also change those properties. Otherwise the binding breaks as soon as your code and the ribbon disagree on the current value of the property.

**Comment by Yumeryu** [comment]
@batzen

I do apologize for that, didn't mean to pressure you in any way. 

Thanks for your reply, I am converting my project, which is using MS ribbon, to Fluent Ribbon, MS Ribbon works with one way, so I didn't realize the issue is actually caused by that. 

I've moved on to something else for a few days, but I will come back to try what you suggested, thanks again.

**Comment by batzen** [comment]
@Yumeryu ping

**Comment by batzen** [comment]
@Yumeryu ping

**Comment by batzen** [comment]
@Yumeryu ping
