### ISSUE TITLE
combobox and dateformat

### ISSUE THREAD

**Issue by bochelie1000** [fluentribbon/Fluent.Ribbon#451]
When the user try to select an item from the combobox for the second time, the first item in the dropdown menu wil be the last selected item. 
 I included a repro in the attachment. By the way this project is still the best!!!
[WpfApplication2.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/1175622/WpfApplication2.zip)

---
### Environment

- Fluent.Ribbon __v5.0.2.46__ or earlier
- Windows 7
- .NET Framework 4.5

**Comment by batzen** [comment]
I am currently at vacation. Will have a look when i am back home.

**Comment by bochelie1000** [comment]
Have a nice vacation. You deserve it. :)

**Comment by batzen** [comment]
Had to adjust the converter to not throw an exception because of an invalid format, but i can select dates fine.
Entering text is impossible because of the converter.

Could you try to reproduce the issue using a regular combobox? If you can reproduce it with that one it's caused by your code and is not a bug in Fluent.Ribbon. The ComboBox in Fluent.Ribbon is inherited from the default WPF ComboBox.

**Comment by batzen** [comment]
@bochelie1000 ping

**Comment by batzen** [comment]
Please note that this only works if the combobox has IsEditable=False. This applies to the standard combobox and the fluent one.
