### ISSUE TITLE
RibbonGroupBox items alignment

### ISSUE THREAD

**Issue by 8VAid8** [fluentribbon/Fluent.Ribbon#502]
How to set <Fluent:RibbonGroupBox> items alignment?
I wanna set TextBox in the center of GroupBox:
` <Fluent:RibbonGroupBox  Header="Filter" >
                    <Fluent:TextBox  Header="Name"
                                        Width="150"
                                        HorizontalAlignment="Center"
                                        VerticalAlignment="Center"
                                        />
                </Fluent:RibbonGroupBox>`
But it doesn't work. How item's alignment can be changed?

![image](https://user-images.githubusercontent.com/10807897/34996453-bac7e596-faea-11e7-9fc4-e554f160e338.png)

---
### Environment

- Fluent.Ribbon __v5.0.2.46
- Windows 10 last
- .NET Framework 4.6

**Comment by batzen** [comment]
The items panel for RibbonGroupBox is a WrapPanel so your best bet would be to use a Grid around your Fluent:TextBox and adjust layout settings on that one and on the textbox.

Using layout settings on the textbox is problematic because ribbon controls, like Fluent:TextBox, are subject to custom layout schemes because they get resized etc. and that's one thing you will loose by wrapping it in a grid. They TextBox will no longer be resized to Large, Middle or Small.

Does that answer your question?

**Comment by 8VAid8** [comment]
Thank you, it works now.
