### ISSUE TITLE
Version 6.0.0.208 not strongly named?

### ISSUE THREAD

**Issue by junrau** [fluentribbon/Fluent.Ribbon#522]
After updating the latest version via NuGet, I get errors that it is not strongly named.  Was this an intentional change?

---
### Environment

- Fluent.Ribbon __v6.0.0.208__
- Windows __7__
- .NET Framework __4.5__

**Comment by batzen** [comment]
It was intentional.

This change was announced in August 2017 with https://github.com/fluentribbon/Fluent.Ribbon/issues/466 and on twitter, gitter and it's the first bold marked entry for breaking changes for version 6 in the [Changelog](https://github.com/fluentribbon/Fluent.Ribbon/blob/develop/Changelog.md).
