### ISSUE TITLE
RadioButtons with SplitButton

### ISSUE THREAD

**Issue by uwebraunholz** [fluentribbon/Fluent.Ribbon#530]
I want to create a group of Radiobuttons, where e.g. 3 out of 5 have a sub selection. Therefore I think a SplitButton for those 3 would make sense. The user can either click on the MainSplitButton or on the Dropdown to select the sub items.
But if I do that the Radiobuttons are not in the same container anymore and therefore out of their RadioButton group.
Is there a way I can get this to work? Thanks!

**Comment by batzen** [comment]
I might not fully understand what you are trying to achieve.
Do you have a small sample application so i can try it out myself?

**Comment by batzen** [comment]
@uwebraunholz ping

**Comment by batzen** [comment]
@uwebraunholz ping

**Comment by uwebraunholz** [comment]
Sorry for the long delay, did not get any notification. I created a picture, that might be better than a sample project.
Imagine all the buttons visible belong to the same RadioButton group. The first 3 big buttons are SplitButtons, so users can choose with one click. I assume the issue is, that the group cannot span across multiple parents.
![tempsnip](https://user-images.githubusercontent.com/7031553/38772366-0dd2bcc2-4035-11e8-8c70-21ebe1a79d6f.png)

**Comment by batzen** [comment]
A repro is, most of the times, better than a screenshot because i can see what you tried to do.

But you are right the groups are tied to `KeyboardNavigation.GetVisualRoot`. As i am just inheriting from the regular wpf `RadioButton` there is not much i can do to change that.

You will have to use code behind to be able to achieve what you want. You could, for example, don't add your buttons to a group (not assigning `GroupName` at all) and then handling the mutual exclusive selection in code behind.

**Comment by batzen** [comment]
@uwebraunholz Did my answer help you to find a working solution for you?

**Comment by uwebraunholz** [comment]
Ok thanks @batzen. I was thinking this might be the answer but was hoping for something I missed :) Thanks for your help.
