### ISSUE TITLE
command

### ISSUE THREAD

**Issue by bochelie1000** [fluentribbon/Fluent.Ribbon#54]
Hallo,

I dont know where to place these kind of questions. I updated from  version 2.1 to 3.2. Now my Commands are not working everywhere. Have something changed about commands?

**Comment by batzen** [comment]
There were changes regarding commands.
One of them was removing IsFocusScope=true from everthing in this library because it caused many other problems.
Could you try to set IsFocusScope=true on the buttons where your commands stopped working?
That change is also listed here: https://github.com/fluentribbon/Fluent.Ribbon/blob/master/ReleaseNotes.md

**Comment by bochelie1000** [comment]
Yes it works. What stupid that i didnt check the realesenotes. Thanks a lot!!
