### ISSUE TITLE
Can't see mahapps Progress Dialog opened from inside a Ribbon Backstage

### ISSUE THREAD

**Issue by hybrid2102** [fluentribbon/Fluent.Ribbon#561]
I'm using mahapps in combo with Fluent.Ribbon.
If I open a mahapps  Progress Dialog from inside a RibbonBackstage, I can't see the dialog. The dialog is actually "alive", but it's invisible (I can notice that looking at some other pieces of my UI).
Works fine outside the RibbonBackstage. Any hint?
Thank you.

---
### Environment

- Visual Studio __2017 v15.6.4__
- Fluent.Ribbon __v6.1.0.233__
- MahApps.Metro __v1.6.0__
- Windows __Server 2012 R2__
- .NET Framework __4.7.1__

**Comment by batzen** [comment]
That's most probably because the backstage is rendered inside an adorner and i guess the progress dialog from MahApps is rendered in an adorner which has a lower z-index.

Could you tell me how you open the progress dialog or even better provide a small repro-application?
Another approach to create a repro would be to modify the MahMetroWindow included in the showcase application of Fluent.Ribbon.

**Comment by hybrid2102** [comment]
I created a small repro-application
[WpfApp4.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/1906712/WpfApp4.zip)

Thanks for the support.

**Comment by batzen** [comment]
Ok, this one will be more difficult as MahApps does not use an adorner to render it's dialogs.
Will try to find a solution.

**Comment by hybrid2102** [comment]
Thank you very much!

Il giorno ven 13 apr 2018 alle ore 12:03 Bastian Schmidt <
notifications@github.com> ha scritto:

**Comment by batzen** [comment]
It's not possible to show a real MahApps progress dialog because the backstage uses an adorner and MahApps uses a completely different approach with containers embedded into the window itself.
These approaches are incompatible. Thus it's the easiest to just show an adorner above the backstage and render a custom progress dialog there.

To give you an idea of how this can be done i added some sample code to the showcase application with https://github.com/fluentribbon/Fluent.Ribbon/commit/60878cc8109f40ec2744a4d24915d7dd6e589d95.
Please have a look at that code and give some feedback ;-)

**Comment by batzen** [comment]
@hybrid2102 ping

**Comment by hybrid2102** [comment]
Sorry, I'm afk, will come back and give feedback this Friday :)
Thanks for the commit

**Comment by hybrid2102** [comment]
I had a look at that code, and this approach is simple and effective, thank you for you commit!
Anyway, I strongly needed to show a real MahApps progress dialog, but I was lucky because of my specific application workflow: the app has to load its cache during the first run while showing the dialog and then show the backstage already open. The workaround was simple: showing the dialog with the backstage closed and then open the backstage immediately after the loading.

**Comment by batzen** [comment]
Glad you found a solution that works for you. ;-)
