### ISSUE TITLE
Assert failure when calling RibbonStateService.Save()

### ISSUE THREAD

**Issue by GeertvanHorrik** [fluentribbon/Fluent.Ribbon#588]
We are getting these assertions on some client machines in release mode.

![image](https://user-images.githubusercontent.com/1246444/43048707-6ecd1ea0-8dec-11e8-99ed-7df607d4de0b.png)

Any idea what could be the cause?

---
### Environment

- Fluent.Ribbon __v6.1.0.233__
- Windows __10__
- .NET Framework __4.7__

**Comment by batzen** [comment]
The full assert message would help a lot.
You should be able to just hit CTRL + C on the dialog.
As far as i can remember i had problems with the isolated storage in the past. Maybe i'll remember what it was caused by if i see the full error.

**Comment by GeertvanHorrik** [comment]
The thing is, this happens only once per machine :) Will try to see if I can reset the assertion (maybe deleting the file).

**Comment by batzen** [comment]
It seems like it crashes because the file does not exist and while getting the error message it throws some assert.
At least that's the only thing i can guess from the stack and referencesource.
The isolated storage file is created with FileMode.Create from fluent.
So it really lokks like an error in .net while throwing an exception.
I guess deleting the file should cause the assert to show up again.

**Comment by GeertvanHorrik** [comment]
Tried deleting the file on my pc  (%localappdata%\IsolatedStorage), didn't cause the error here. Will investigate a bit more.

**Comment by GeertvanHorrik** [comment]
Did some more investigation. The ticket was created on May 1, 2018. Maybe it has been fixed in a more recent update? I asked all devs to clear this setting, no one can reproduce. Whenever we come across this, I will re-open. 

Thanks!
