### ISSUE TITLE
Ribbon in MahApp.MetroWindow

### ISSUE THREAD

**Issue by EMostafaAli** [fluentribbon/Fluent.Ribbon#608]
I am following the steps in this [link ](https://fluentribbon.github.io/documentation/interop_with_MahApps.Metro)to add fluent ribbon to Metro Window. Everything works fine except for theme sync.

More specifically, this line doesn't compile indicating the "Theme" is not a member of args.
`var fluentRibbonTheme = args?.Theme ?? ThemeManager.DetectTheme();`

Not sure if the document needs to be updated or I am missing something here.

---
### Environment

- Fluent.Ribbon __v6.1.0.326__
- Windows __10__ version 1803
- .NET Framework __4.6.1__

**Comment by batzen** [comment]
That's because i changed the Theming in version 7 (which is currently available as preview) and the sample uses the new code.
The theming in MahApps.Metro will also change to the same mechanism in version 2.
The "old" code should be available in the master branch. Will add both ways and notices about version availability to the documentation later today. Sorry for the confusion.
