### ISSUE TITLE
try to set ribbon background color

### ISSUE THREAD

**Issue by ethernith** [fluentribbon/Fluent.Ribbon#609]
I'm trying to set background color of whole ribbon.

`<Fluent:Ribbon HorizontalAlignment="Stretch" VerticalAlignment="Stretch" Background="#FFF1F1F1">
</Fluent:Ribbon>`

or

`<SolidColorBrush x:Key="Fluent.Ribbon.Brushes.Ribbon.Background">#FFF1F1F1</SolidColorBrush>`

but it does not work

---
### Environment

- Fluent.Ribbon v7.0.0-alpha0388
- Windows 10
- .NET Framework 4.6.1

**Comment by batzen** [comment]
That's because the ribbon itself is the lowest layer and there are quite a few layers above the ribbon.
Have a look at https://github.com/fluentribbon/Fluent.Ribbon/blob/develop/Fluent.Ribbon.Showcase/RibbonWindowColorized.xaml to get a feeling for which colors you can/should override to get your desired effect.
Feel free to ask any questions along your way.

**Comment by batzen** [comment]
@ethernith did that answer your question?

**Comment by ethernith** [comment]
Yes. Thx!
