### ISSUE TITLE
Office2013 Icon fixing

### ISSUE THREAD

**Issue by yang-er** [fluentribbon/Fluent.Ribbon#63]
I found a way to make the icon shown in the title bar clear, but I don't know how to send a patch.
Just open Themes\Office2013\RibbonWindow.xaml, then find the "PART_Icon" and change its Margin to "8,1,0,0", and the Icon will be clear.

By the way, I find it possible to enable "Touching Mode", changing the margin and size in the xaml of controls, but it seems too hard for me to change many files. 

My English isn't very good..

**Comment by batzen** [comment]
The icon issue should have been fixed with #50 already, are you sure that you are using at least version 3.3?

Regarding "Touch mode", I don't need it and it requires quite a lot of work, so feel free to implement it in a way that takes all three themes (Office 2010, Office 2013 and Windows 8) into account. ;-)

**Comment by yang-er** [comment]
Yes, it is 3.3.0(SRC). But it doesn't work well on my computer.It's still blurred.

**Comment by batzen** [comment]
Will have a look at it.
