### ISSUE TITLE
Setting Header for MenuItem in ApplicationMenu does not work

### ISSUE THREAD

**Issue by nicwe** [fluentribbon/Fluent.Ribbon#725]
In the following case the Header of a MenuItem in the ApplicationMenu won't be set.
I specified the following in the XAML of the window.
```XAML
<Window.Resources>
  <Style TargetType="{x:Type Fluent:MenuItem}">
    <Setter Property="Header" Value="{Binding Header}"/>
  </Style>
</Window.Resources>
```
If I set the DataContext for a MenuItem in the ApplicationMenu to a object with a Header property, the MenuItem has no Text.
If I set the DataContext for a MenuItem in a RibbonGroupBox or SplitButton to a object with a Header property, the MenuItem has the expected text.

I think this is a general problem because I have the same behavior at the IsChecked property.

---
### Environment

- Fluent.Ribbon __v7.0.0.0__ (develop)
- Windows __10__
- .NET Framework __4.5.2__

**Comment by batzen** [comment]
That's because you have to also overwrite the styles for Fluent:MenuItem with the keys `ApplicationMenuSecondLevelStyle` and `ApplicationMenuStyle`.
Although the names are quite bad...
Will change the names/keys to `Fluent.Ribbon.Styles.ApplicationMenu.MenuItem` and `Fluent.Ribbon.Styles.ApplicationMenu.MenuItemSecondLevel` later today.
