### ISSUE TITLE
InRibbonGallery Resizing  Issues

### ISSUE THREAD

**Issue by pschimmel** [fluentribbon/Fluent.Ribbon#765]
Hi!

I've created a sample project with some InRibbonGalleries and found some problems related to the resizing of the galleries.

The main setup looks like this:

![image](https://user-images.githubusercontent.com/9028723/70848454-35722700-1e72-11ea-8898-6a1f520ec1ca.png)

There are three galleries in one group. The only difference between the first two and the last one is the size of the items in the gallery. In the first galleries, each item height is set to a fixed size of 56. Thus each item fills the height of the collapsed gallery. 

In the third gallery, the item height is not defined and therefore the items are shown stacked in the collapsed gallery. 

Still I would expect that the width of the third gallery is wider than just one column, as there is enough space left in the tab to expand to the right.

For each gallery the setting of Min and Max items per row is set to 
`MaxItemsInRow="6" MinItemsInRow="4"`

But when I reduce the width of my window, the first two galleries reduce to a size smaller that 4 items per row:

![image](https://user-images.githubusercontent.com/9028723/70848478-8c77fc00-1e72-11ea-8932-a40969dde92b.png)

The third problem is that under no circumstances, the galleries would collapse to a DropDownButton, although the CanCollapseToButton is set to "true".

Here's the sample project:
[FluentTest.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/3963815/FluentTest.zip)

PS: In the main window of the sample project click on the 2nd button.

---
### Environment

- Fluent.Ribbon v7.0.1
- Windows 10
- .NET Framework 4.7.2

**Comment by batzen** [comment]
You are right.
The size reduction code also decreases `MinItemsInRow` when decreasing.
It should instead just decrease `MaxItemsInRow` till it's equal to `MinItemsInRow` and collapse or stop reducing if that point is reached.
The same for when increasing the size but with `MaxItemsInRow` as the max.
I don't know why the code does it the way it's currently is.
But thinking about the current code it just seems wrong.

The reason why your test application does not collapse the galleries is because your `ReduceOrder` is missing one more `,(FirstGalleryGroup)`. That's of course caused by the reduction code reducing the allowed items in one row below `MinItemsInRow`.

The reason why the third gallery does not show as many items in one row as you'd like it to is because the code does only apply the fixed `ItemWidth` if `ItemHeight` is also set.
The right way for the code to handle this is to always use the supplied fixed values and only use calculated values for width/height if there is none set.

I personally never used the gallery in any of my applications, i guess that's why those bugs are still there.

**Comment by batzen** [comment]
What makes your third gallery look even worse (only having one item per row) is that the bug in the item width calculation confuses the remaining size calculation code.

**Comment by pschimmel** [comment]
There is one more thing I discovered:

Then I use the InRibbonGallery in a DataTemplate, the size changing does not happen at all.
I've updated the testing project (This time press button 1):

[FluentTest2.zip](https://github.com/fluentribbon/Fluent.Ribbon/files/3963957/FluentTest2.zip)

**Comment by batzen** [comment]
The issue with that one is that WPF does not generate the `InRibbonGallery` directly from the `DataTemplate` but a `ContentPresenter` which contains the `InRibbonGallery` instead.
That's an issue i've ran into every time i try to improve the binding capabilities of some part of the ribbon.
But it's separate from the real sizing issue.
Could you create a new issue for that and attach your sample project there?
Then i can tackle and track both issues separately.

**Comment by pschimmel** [comment]
Sure. I've created a new issue.
