### ISSUE TITLE
Additional line in menu item popup

### ISSUE THREAD

**Issue by fialo4ka** [fluentribbon/Fluent.Ribbon#778]
Additional line in button group popup
Hello! could you please help me to resolve this line!
I create demo app it contain some changes from real app, but may be it will be simplest to understand were is the problem!

![image](https://user-images.githubusercontent.com/36087929/74819471-ba5d3f00-5300-11ea-8775-4406faec4542.png)

In real app:
![image](https://user-images.githubusercontent.com/36087929/74819543-da8cfe00-5300-11ea-8fed-bd6b800744f4.png)
![image](https://user-images.githubusercontent.com/36087929/74820219-ee852f80-5301-11ea-9043-3066ed2dd856.png)

Also in app I overwrite
x:Key="Fluent.Ribbon.Brushes.RibbonTabItem.BorderBrush
x:Key="Fluent.Ribbon.Brushes.Ribbon.Background"

---
### Environment

    Fluent.Ribbon v7.0.1
    Windows 10
    .NET Framework 4.8

**Comment by fialo4ka** [comment]
https://github.com/fialo4ka/FluentRibbon.Project

**Comment by batzen** [comment]
That happens because the default itemtemplate is MenuItem. Will try to have a look at your sample as soon as I can.

**Comment by batzen** [comment]
Finally had time to have a look at your code.
The issue is that you are creating buttons as child elements for a menu item.
This causes your button to be rendered inside a menu item as the default item container for children of a menu item is `MenuItem`.
If you change your code to create a `MenuItem` instead of `GISRibbonButton` it will work without the line.
If you want those menu items to be as large as your button is you should be able to set a custom style for those menu items.
