### ISSUE TITLE
Margin on top of backstage during reopening Startscreen

### ISSUE THREAD

**Issue by Offline-R503B** [fluentribbon/Fluent.Ribbon#892]
When reopening the startscreen with the code provided in the example there is a margin on top of the backstage. 

Thus showing part of the Startscreen before the Backstage is properly "hidden"

![](https://files.gitter.im/5628c51216b6c7089cb7e069/lrcz/Giff.gif)

---
### Environment

- 
![image](https://user-images.githubusercontent.com/11785451/104965151-63635c80-59de-11eb-80fb-a76df07aa0f3.png)
__
- Windows __10__
- .NET Framework __5.0

**Comment by batzen** [comment]
@Offline-R503B Just had a look at this and finally remembered why this happens.
The Backstage has a margin for the content part so that the titlebar is still visible when it's open.
You can change the margin by changing `SelectedContentMargin` on the `BackstageTabControl`.
Setting it to 0 should solve your issue, but be aware that this causes the titlebar to be completely covered when the backstage is open.

**Comment by Offline-R503B** [comment]
I will try that right away! Thanks for looking into it. Will post back my results 👍

**Comment by Offline-R503B** [comment]
> I will try that right away! Thanks for looking into it. Will post back my results 👍

@batzen Works perfectly! Thank you! 🥇  Looks a lot smoother now :3
