### ISSUE TITLE
Window chrome turning black during window resize.

### ISSUE THREAD

**Issue by abdelkarim** [fluentribbon/Fluent.Ribbon#90]
Start by watching the following [video](https://vimeo.com/124054698), how to reproduce ?
1. launch the test app and switch to the office 2010 blue theme
2. move it below the task bar a little bit.
3. start re-sizing and notice how it turns black.

**Comment by batzen** [comment]
That's really strange and only happens when making the window wider by using the re-size border on the right side, but not when using the top or left re-size border...

This bug/issue is definitely on the microsoft side of the fence... 

I guess I will have to sit down and report all the WindowChrome issues we encounter here (there are a few other open issues) to microsoft connect.

**Comment by batzen** [comment]
I don't know how to fix the current issues, including this one, related to the microsoft WindowChrome class. Any suggestions from anyone?

**Comment by loewnzaan** [comment]
Hey,
here is a workaround:
public WindowSizing(RibbonWindow window)
        {
            this.window = window;
            this.window.StateChanged += this.HandleWindowStateChanged;
        }

In WindowSizing add a SizeChanged-Event. This Event call the HandleWindowStateChanged. When the Window not responds, after the not responding the SizeChanged event was called and set the position of the window correct again!

**Comment by batzen** [comment]
This can't be the solution because "FixNastyWindowChromeBug" (which is called by "HandleWindowStateChanged") checks if the window is maximized and if it's not the function just returns.

**Comment by batzen** [comment]
Does this still happen on your machines?
I just tried it on Windows 10 and the issues seems to be solved.

**Comment by batzen** [comment]
Should be fixed in develop branch.
