### ISSUE TITLE
Problems when compiling: metadata files missing and RibbonWindow not recognized.

### ISSUE THREAD

**Issue by fernandoagomezf** [fluentribbon/Fluent.Ribbon#903]
Hi, I downloaded today the project, opened the solution file using VS2019, and tried to compile as-is, and got lots of errors, ranging from "Metadata file [...]\Fluent.dll  could not be found", to "The name RibbonWindow' does not exist in the namespace urn:fluent-ribbon". Here's a screenshot of my environment. 

![image](https://user-images.githubusercontent.com/10499474/109233903-55002180-7790-11eb-9b42-15d5699c087c.png)

The project Fluent.Ribbon did compile correctly, it's only the Fluent.Ribbon.Showcase and Fluent.Ribbon.Tests projects that did not compile. Do I have to do any other configuration? I noticed a directory called Build that has a PowerShell file and lots of other files I do not recognize, so I'm not sure if I'm supposed to edit any of those. 

Thanks in advance!

**Comment by batzen** [comment]
Hi, you are only showing the last failed steps of the compile chain.
The root issue will, most likely, be that the compile of "Fluent.Ribbon" failed and "Fluent.Ribbon.Showcase" just fails to compile because it depends on it.
Could you try to pull the latest changes from the git repo and open the solution again?
It should now prompt to install any missing components.

If it does not or you are still unable to compile after installing missing components, please call "./Build.ps1" in the root folder any copy it's output to this issue.

**Comment by fernandoagomezf** [comment]
Hi, thanks for the reply! As I said in my post, Fluent.Ribbon does compile without problems, at first I thought that might be the case and then I built Fluent.Ribbon only and it finished without any error or warning. Will try to download again all the repo and the PowerShell as suggested and see if that solves the issue. Thanks again!!

**Comment by fernandoagomezf** [comment]
Hi, I downloaded the repo again, and still getting the same problem (still Fluent.Ribbon is compiling but not Showcast nor Tests). I tried running the PowerShell script but I'm getting a few errors:

"Exception while resolving assembly System.Runtime.Loader"
"Exception while resolving assembly Microsoft.CodeAnalysis.CSharp.resources"
"System.IO.DirectoryNotFoundException: Can't find the .git directory in C:[Dir where I downloaded the code]"

This is a screenshot (some bits are in Spanish but it basically says that some files are not found):
![image](https://user-images.githubusercontent.com/10499474/109343252-a95bdd80-7832-11eb-9ec8-bc5eca881e8c.png)

Also, I clicked the "clean solution" command and got these errors, which I suppose happen because the build failed, but still I'm including them just in case:
![image](https://user-images.githubusercontent.com/10499474/109343574-2f782400-7833-11eb-8e4f-d8998883311b.png)

**Comment by fernandoagomezf** [comment]
Huh. I tried opening the project properties and it's got the target framework blank and disabled... I've never seen this before
![image](https://user-images.githubusercontent.com/10499474/109344582-88948780-7834-11eb-950f-345c34033417.png)

Also, when I open the Manage NuGet package for Fluent.Ribbon project, I'm getting an error:
![image](https://user-images.githubusercontent.com/10499474/109344909-fd67c180-7834-11eb-9201-066bd85bdf3a.png)

I'm getting the feeling that I'm missing components, do I need to have any other software installed apart from Visual Studio 2019? Thanks again!

**Comment by batzen** [comment]
The build-script fails because you downloaded the code and didn't use git.
=> Will fix that in the future.

The target frameworks are grayed out because there is not one target framework for Fluent.Ribbon but 4 instead (net452, net462, netcoreapp3.1 and net5.0).

The package manager UI in studio might fail because Fluent.Ribbon uses CPVM (central package version management) to define global versions for all referenced nuget packages.

The only additional software you have to have installed is the .NET 5.0 SDK, but that should be installed by Visual Studio 2019, if you are using an up to date version (at least 16.8).

Could you try to run `dotnet build` instead of `build.ps1`?

**Comment by mrk10000** [comment]
Hello, i have installed all sdk, tried the same but still a lot of compilation issues, tried to install through package manager and indeed version error, is there a branch that i can take i can compile?, thanks

I have tried branch master an develop, both failed, is there any enviroment variable i need to set to make it work?

I am using VS2019

![image](https://user-images.githubusercontent.com/47640813/115501729-59e5cc80-a239-11eb-9966-039af68c0958.png)
![image](https://user-images.githubusercontent.com/47640813/115501978-ce207000-a239-11eb-94e7-792c56199e01.png)

**Comment by batzen** [comment]
@mrk10000 Which exact version of visual studio are you using?
Does it work when you run `build.ps1` or `build.cmd`?

**Comment by mrk10000** [comment]
Thanks for the response, it is working now thanks anyway :)
