### ISSUE TITLE
In edit mode of the WPF window, the ribbon button images do not appear correctly.

### ISSUE THREAD

**Issue by Perpete** [fluentribbon/Fluent.Ribbon#911]
Hello,
Here is my working environment with Fluent.Ribbon:
Fluent.Ribbon: 8.0.3
Windows: 10
.NET Framework: 4.8
Visual studio: 16.9.0
Development: WPF with VB.net

In edit mode of the WPF window, the ribbon button images do not appear correctly.
They are represented by a red circle with a white cross as if the link to my images is not correct. The same images in an image control are displayed well.
In program run mode, the ribbon button images appear correctly.

Is this normal?

![Ribbon](https://user-images.githubusercontent.com/66659162/110248323-baae9380-7f70-11eb-99b1-8f89099bfbe9.png)

**Comment by batzen** [comment]
That's because the designer is running it's own application and does not provide the resources correctly.
There are ways to solve this in the ribbon library, but most of the parts to get this working during design time are internal to the .NET framework. Will try to solve this but i won't promise to get this fixed soon.

**Comment by batzen** [comment]
I tried a lot of things to get this fixed, but there is no way to fix this as the designer process is not providing information about the current context (project, assembly etc.).
It only works for Image and it's source because there is a type converter which preserves this information during BAML compile time, as far as i found out.
If you want this to work you should report this issue to Microsoft or use a fully qualified "pack" URI (including the assembly).
Sample for fully qualified "pack" URI `pack://application:,,,/Fluent.Ribbon.Showcase;component/Images/Red.png`

**Comment by Perpete** [comment]
thank you for your reply.
